# Generated by Django 6.0.3 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FuelPriceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=20)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("gasoline", "Gasoline"), ("diesel", "Diesel"), ("lpg", "LPG")],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("source", models.CharField(default="collectapi", max_length=50)),
                ("is_current", models.BooleanField(default=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["country", "fuel_type", "is_current"], name="common_fuel_country_640d31_idx"),
                    models.Index(fields=["created_at"], name="common_fuel_created_14a98b_idx"),
                ],
            },
        ),
    ]
