# Generated by Django 6.0.3 on 2026-03-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelpricesnapshot',
            new_name='common_fuel_country_ce3fb0_idx',
            old_name='common_fuel_country_640d31_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelpricesnapshot',
            new_name='common_fuel_created_025bf8_idx',
            old_name='common_fuel_created_14a98b_idx',
        ),
    ]
