# Generated by Django 6.0.3 on 2026-03-16 14:43

import django.core.validators
import django.db.models.deletion
import vehicles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15, unique=True, validators=[vehicles.validators.validate_plate_number])),
                ('brand', models.CharField(max_length=50)),
                ('photo_url', models.URLField(blank=True, help_text='Link to a vehicle photo', null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Capacity in kilograms', validators=[django.core.validators.MinValueValidator(100)])),
                ('fuel_consumption', models.DecimalField(decimal_places=2, help_text='Liters per 100km', max_digits=5, validators=[vehicles.validators.validate_fuel_consumption])),
                ('vehicle_type', models.CharField(choices=[('tank', 'Tank Truck'), ('refrigerated', 'Refrigerated Truck'), ('regular', 'Regular Truck'), ('express', 'Express Van')], max_length=20)),
                ('drivers', models.ManyToManyField(blank=True, related_name='vehicles', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='ExpressVan',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('max_parcel_count', models.IntegerField(help_text='Maximum number of parcels')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='RefrigeratedTruck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('min_temperature', models.IntegerField(help_text='Minimum cooling temperature in Celsius')),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='RegularTruck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('trailer_attached', models.BooleanField(default=False)),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.CreateModel(
            name='TankTruck',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vehicles.vehicle')),
                ('liquid_type', models.CharField(help_text='Type of liquid transported', max_length=50)),
            ],
            bases=('vehicles.vehicle',),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='vehicles_ve_plate_n_a3accc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_ve_vehicle_76fbe4_idx'),
        ),
    ]
