# Generated by Django 6.0.3 on 2026-03-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(choices=[('tank', 'Tank Truck'), ('refrigerated', 'Refrigerated Truck'), ('regular', 'Regular Truck'), ('express', 'Express Van')], default='regular', max_length=20)),
                ('distance_km', models.PositiveIntegerField(help_text='Distance between origin and destination in kilometers')),
                ('cargo_weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price charged to the client', max_digits=10)),
                ('fuel_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel price in EUR per liter at time of delivery', max_digits=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vehicles.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
