# Generated by Django 6.0.3 on 2026-03-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance_km', models.PositiveIntegerField(help_text='Distance between origin and destination in kilometers')),
                ('cargo_weight', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price charged to the client', max_digits=10)),
                ('fuel_price', models.DecimalField(decimal_places=2, help_text='Fuel price in EUR per liter at time of delivery', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vehicles.vehicle')),
            ],
        ),
    ]
